[package]
name = "starkmole"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.9.4"
openzeppelin = "1.0.0"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
fmt = "scarb fmt"
build = "scarb build"

[dev-dependencies]
snforge_std = "0.40.0"
assert_macros = "2.9.4"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]