[package]
name = "starkmole"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
fmt = "scarb fmt"
build = "scarb build"
